import {
  AlertTriangle,
  BarChart3,
  Clock3,
  FileText,
  Lightbulb,
  LineChart,
  Shield,
  Wrench,
} from "lucide-react";

import {
  formatClockTime,
  formatDurationMs,
  formatIncidentDate,
  formatTimelineTimestamp,
} from "../utils/incidentFormat";
import { CategoryBadge, SeverityBadge } from "./IncidentBadges";

function confidencePercent(value) {
  if (value === null || value === undefined || Number.isNaN(Number(value))) return null;
  const num = Number(value);
  return num <= 1 ? Math.round(num * 100) : Math.round(num);
}

function asList(value) {
  if (!value) return [];
  if (Array.isArray(value)) return value;
  return [value];
}

function Section({ title, children }) {
  return (
    <section className="space-y-3">
      <h3
        className="text-xs font-semibold uppercase tracking-wide"
        style={{ color: "var(--app-text-muted)" }}
      >
        {title}
      </h3>
      {children}
    </section>
  );
}

function ConfidenceBar({ value }) {
  const pct = confidencePercent(value);
  if (pct === null) {
    return <span style={{ color: "var(--app-text-muted)" }}>—</span>;
  }

  return (
    <div className="flex items-center gap-3">
      <div
        className="h-2.5 flex-1 overflow-hidden rounded-full"
        style={{ backgroundColor: "var(--app-nav-hover)" }}
        role="progressbar"
        aria-valuenow={pct}
        aria-valuemin={0}
        aria-valuemax={100}
      >
        <div
          className="h-full rounded-full transition-all"
          style={{
            width: `${pct}%`,
            background:
              "linear-gradient(90deg, var(--app-brand) 0%, var(--app-brand-secondary) 100%)",
          }}
        />
      </div>
      <span className="min-w-[3rem] text-right text-sm font-semibold">{pct}%</span>
    </div>
  );
}

function recommendationImpact(index) {
  if (index === 0) {
    return { label: "High", color: "var(--app-danger)", dot: "🔴" };
  }
  if (index === 1) {
    return { label: "Medium", color: "var(--app-warning)", dot: "🟡" };
  }
  return { label: "Low", color: "var(--app-success)", dot: "🟢" };
}

function preventionMeta(index) {
  const icons = [
    { Icon: Shield, label: "Protect" },
    { Icon: BarChart3, label: "Monitor" },
    { Icon: LineChart, label: "Improve" },
  ];
  return icons[index % icons.length];
}

function formatModelLabel(modelVersion) {
  if (!modelVersion) return "AI";
  return String(modelVersion)
    .replace(/-\d{4}-\d{2}-\d{2}$/, "")
    .replace(/^gpt-/i, "GPT-");
}

export default function AiAnalysisCard({ incident, analysisDurationSec = null }) {
  const timeline = asList(incident.timeline);
  const evidence = asList(incident.evidence);
  const recommendations = asList(incident.recommendations);
  const prevention = asList(incident.prevention);
  const affectedServices = asList(
    incident.affectedServices ?? (incident.affectedService ? [incident.affectedService] : [])
  );
  const latestAi = asList(incident.aiResponses).sort(
    (a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0)
  )[0];
  const modelVersion = latestAi?.modelVersion || null;
  const confidence = confidencePercent(incident.confidence);

  const durationLabel =
    formatDurationMs(incident.analysisDurationMs) ||
    (analysisDurationSec != null ? `${Number(analysisDurationSec).toFixed(2)} sec` : null);

  const hasAnalysis =
    incident.summary ||
    incident.category ||
    incident.severity ||
    incident.rootCause ||
    timeline.length > 0;

  return (
    <section
      className="space-y-5 rounded-2xl border p-5 md:p-6"
      style={{
        backgroundColor: "var(--app-bg-elevated)",
        borderColor: "var(--app-border)",
      }}
    >
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-base font-semibold">AI Analysis</h2>
          <p className="mt-1 text-sm" style={{ color: "var(--app-text-muted)" }}>
            Generated by {formatModelLabel(modelVersion)}
            {incident.analyzedAt ? ` · ${formatIncidentDate(incident.analyzedAt)}` : ""}
            {durationLabel ? ` · ${durationLabel}` : ""}
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <SeverityBadge severity={incident.severity} />
          <CategoryBadge category={incident.category} />
        </div>
      </div>

      {!hasAnalysis ? (
        <p className="text-sm" style={{ color: "var(--app-text-muted)" }}>
          No AI analysis yet. Click Analyze with AI to investigate this incident.
        </p>
      ) : (
        <>
          <div className="grid gap-4 md:grid-cols-2">
            <div
              className="rounded-xl border p-4"
              style={{ borderColor: "var(--app-border)" }}
            >
              <p
                className="text-xs font-semibold uppercase tracking-wide"
                style={{ color: "var(--app-text-muted)" }}
              >
                Summary
              </p>
              <p
                className="mt-2 text-[18px] font-medium leading-relaxed"
                style={{ color: "var(--app-text)" }}
              >
                {incident.summary || "—"}
              </p>
            </div>
            <div
              className="rounded-xl border p-4"
              style={{ borderColor: "var(--app-border)" }}
            >
              <p
                className="text-xs font-semibold uppercase tracking-wide"
                style={{ color: "var(--app-text-muted)" }}
              >
                Confidence
              </p>
              <div className="mt-4">
                <ConfidenceBar value={incident.confidence} />
              </div>
            </div>
          </div>

          <div
            className="rounded-xl border p-4 md:p-5"
            style={{
              backgroundColor: "color-mix(in srgb, var(--app-warning) 10%, var(--app-bg-elevated))",
              borderColor: "color-mix(in srgb, var(--app-warning) 35%, var(--app-border))",
            }}
          >
            <div className="flex items-start gap-3">
              <span
                className="mt-0.5 flex h-11 w-11 shrink-0 items-center justify-center rounded-xl"
                style={{
                  backgroundColor: "color-mix(in srgb, var(--app-warning) 18%, transparent)",
                  color: "var(--app-warning)",
                }}
              >
                <AlertTriangle size={22} />
              </span>
              <div>
                <p className="text-sm font-semibold" style={{ color: "var(--app-warning)" }}>
                  Root Cause
                </p>
                <p className="mt-2 text-sm leading-relaxed md:text-[15px]">
                  {incident.rootCause || "—"}
                </p>
              </div>
            </div>
          </div>

          {affectedServices.length > 0 && (
            <Section title="Affected Services">
              <div className="flex flex-wrap gap-2">
                {affectedServices.map((service) => (
                  <CategoryBadge key={String(service)} category={service} />
                ))}
              </div>
            </Section>
          )}

          <Section title="Timeline">
            {timeline.length ? (
              <ol className="relative space-y-0">
                {timeline.map((item, index) => {
                  const stamp = formatTimelineTimestamp(item?.timestamp);
                  return (
                    <li key={index} className="relative flex gap-3 pb-5 last:pb-0">
                      {index < timeline.length - 1 && (
                        <span
                          className="absolute left-[15px] top-8 h-[calc(100%-1.5rem)] w-px"
                          style={{ backgroundColor: "var(--app-border)" }}
                          aria-hidden="true"
                        />
                      )}
                      <span
                        className="relative z-10 flex h-8 w-8 shrink-0 items-center justify-center rounded-full border"
                        style={{
                          backgroundColor: "var(--app-bg-elevated)",
                          borderColor: "var(--app-border)",
                          color: "var(--app-brand)",
                        }}
                      >
                        <Clock3 size={14} />
                      </span>
                      <div className="min-w-0 pt-0.5">
                        <p className="text-xs font-semibold" style={{ color: "var(--app-text-muted)" }}>
                          {stamp.date}
                        </p>
                        {stamp.time && (
                          <p className="text-[11px]" style={{ color: "var(--app-text-muted)" }}>
                            {stamp.time}
                          </p>
                        )}
                        <p className="mt-1.5 text-sm leading-relaxed">
                          {item?.event || item?.description || String(item)}
                        </p>
                      </div>
                    </li>
                  );
                })}
              </ol>
            ) : (
              <p className="text-sm" style={{ color: "var(--app-text-muted)" }}>—</p>
            )}
          </Section>

          <Section title="Evidence">
            {evidence.length ? (
              <div className="space-y-3">
                {evidence.map((item, index) => (
                  <article
                    key={index}
                    className="overflow-hidden rounded-xl border"
                    style={{ borderColor: "var(--app-border)" }}
                  >
                    <div
                      className="flex items-center gap-2 border-b px-3 py-2 text-xs font-semibold uppercase tracking-wide"
                      style={{
                        backgroundColor: "var(--app-nav-hover)",
                        borderColor: "var(--app-border)",
                        color: "var(--app-text-muted)",
                      }}
                    >
                      <FileText size={13} />
                      Log Snippet
                    </div>
                    <pre
                      className="overflow-x-auto whitespace-pre-wrap px-3 py-3 font-mono text-xs leading-relaxed"
                      style={{
                        color: "var(--app-text)",
                        backgroundColor: "color-mix(in srgb, var(--app-text) 3%, transparent)",
                      }}
                    >
                      {item?.log || String(item)}
                    </pre>
                    {item?.explanation && (
                      <div
                        className="border-t px-3 py-3"
                        style={{
                          borderColor: "var(--app-border)",
                          backgroundColor:
                            "color-mix(in srgb, var(--app-brand) 8%, var(--app-bg-elevated))",
                        }}
                      >
                        <p
                          className="inline-flex items-center gap-1.5 text-xs font-semibold"
                          style={{ color: "var(--app-brand)" }}
                        >
                          <Lightbulb size={13} />
                          Explanation
                        </p>
                        <p className="mt-1.5 text-sm leading-relaxed">{item.explanation}</p>
                      </div>
                    )}
                  </article>
                ))}
              </div>
            ) : (
              <p className="text-sm" style={{ color: "var(--app-text-muted)" }}>—</p>
            )}
          </Section>

          <Section title="Recommendations">
            {recommendations.length ? (
              <div className="grid gap-3 sm:grid-cols-2">
                {recommendations.map((item, index) => {
                  const impact = recommendationImpact(index);
                  const text = typeof item === "string" ? item : JSON.stringify(item);
                  return (
                    <article
                      key={index}
                      className="rounded-xl border p-4"
                      style={{ borderColor: "var(--app-border)" }}
                    >
                      <div className="flex items-start gap-3">
                        <span
                          className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg"
                          style={{
                            backgroundColor: "color-mix(in srgb, var(--app-brand) 12%, transparent)",
                            color: "var(--app-brand)",
                          }}
                        >
                          <Wrench size={15} />
                        </span>
                        <div className="min-w-0">
                          <p className="text-sm font-semibold leading-snug">{text}</p>
                          <p
                            className="mt-2 inline-flex items-center gap-1.5 text-xs font-semibold"
                            style={{ color: impact.color }}
                          >
                            <span aria-hidden="true">{impact.dot}</span>
                            {impact.label}
                          </p>
                        </div>
                      </div>
                    </article>
                  );
                })}
              </div>
            ) : (
              <p className="text-sm" style={{ color: "var(--app-text-muted)" }}>—</p>
            )}
          </Section>

          <Section title="Prevention">
            {prevention.length ? (
              <ul className="space-y-2">
                {prevention.map((item, index) => {
                  const { Icon } = preventionMeta(index);
                  const text = typeof item === "string" ? item : JSON.stringify(item);
                  return (
                    <li
                      key={index}
                      className="flex items-start gap-3 rounded-lg border px-3 py-2.5 text-sm"
                      style={{ borderColor: "var(--app-border)" }}
                    >
                      <span
                        className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-md"
                        style={{
                          backgroundColor: "color-mix(in srgb, var(--app-success) 12%, transparent)",
                          color: "var(--app-success)",
                        }}
                      >
                        <Icon size={14} />
                      </span>
                      <span className="leading-relaxed">{text}</span>
                    </li>
                  );
                })}
              </ul>
            ) : (
              <p className="text-sm" style={{ color: "var(--app-text-muted)" }}>—</p>
            )}
          </Section>

          <Section title="AI Metadata">
            <div
              className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-4"
              style={{ borderColor: "var(--app-border)" }}
            >
              <div>
                <p className="text-xs" style={{ color: "var(--app-text-muted)" }}>
                  Model
                </p>
                <p className="mt-1 text-sm font-semibold">{formatModelLabel(modelVersion)}</p>
              </div>
              <div>
                <p className="text-xs" style={{ color: "var(--app-text-muted)" }}>
                  Started
                </p>
                <p className="mt-1 text-sm font-semibold">
                  {formatClockTime(incident.analysisStartedAt)}
                </p>
              </div>
              <div>
                <p className="text-xs" style={{ color: "var(--app-text-muted)" }}>
                  Completed
                </p>
                <p className="mt-1 text-sm font-semibold">
                  {formatClockTime(incident.analyzedAt)}
                </p>
              </div>
              <div>
                <p className="text-xs" style={{ color: "var(--app-text-muted)" }}>
                  Analysis Time
                </p>
                <p className="mt-1 text-sm font-semibold">{durationLabel || "—"}</p>
              </div>
              <div>
                <p className="text-xs" style={{ color: "var(--app-text-muted)" }}>
                  Confidence
                </p>
                <p className="mt-1 text-sm font-semibold">
                  {confidence === null ? "—" : `${confidence}%`}
                </p>
              </div>
              <div>
                <p className="text-xs" style={{ color: "var(--app-text-muted)" }}>
                  Generated
                </p>
                <p className="mt-1 text-sm font-semibold">
                  {incident.analyzedAt ? formatIncidentDate(incident.analyzedAt) : "—"}
                </p>
              </div>
            </div>
          </Section>
        </>
      )}
    </section>
  );
}
